  - name: Instalação Jenkins
    hosts: jenkins
    remote_user: root
    tasks:
    - name: Instalação Java
      ansible.builtin.apt:
        name: openjdk-17-jdk
        state: present
        update_cache: yes

    - name: Adicionando a chave do repositório jenkins
      ansible.builtin.apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
        state: present

    - name: Adicionando o REPOSITÓRIO jenkins
      ansible.builtin.apt_repository:
        repo: deb https://pkg.jenkins.io/debian-stable binary/
        state: present

    - name: Instalação Jenkins
      ansible.builtin.apt:
        name: jenkins
        state: present
        update_cache: yes

    - name: Coleta senha inicial jenkins#
      ansible.builtin.command: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: senha
      ignore_errors: yes

    - name: Mostrar senha inicial jenkins
      ansible.builtin.debug:
        msg: "{{ senha.stdout }}"
      when: senha.stdout != ""

  - name: Instalação Docker
    hosts: jenkins
    remote_user: root
    tasks:
    - name: Instalação pré-requisitos Docker
      apt:
        name: ca-certificates, curl, gnupg, lsb-release
        state: present
        update_cache: yes

    - name: Adicionando a chave do repositório Docker
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Adicionando o REPOSITÓRIO Docker
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Instalação Docker
      ansible.builtin.apt:
        name: docker-ce, docker-ce-cli, containerd.io
        state: present
        update_cache: yes

    - name: Adicionando o usuario jenkins ao grupo Docker
      ansible.builtin.user:
        name: jenkins
        groups: docker
        state: present
        append: yes

    - name: Restart Jenkins
      ansible.builtin.service:
        name: jenkins
        state: restarted

  - name: Instalação Kubectl
    hosts: jenkins
    tasks:
    - name: Instalação pre-requisitos Kubectl
      ansible.builtin.apt:
        name: ca-certificates, curl
        state: present
        update_cache: yes

    - name: Adicionando a chave do repositório Kubernetes
      ansible.builtin.apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Adicionando o REPOSITÓRIO Kubernetes
      ansible.builtin.apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present

    - name: Instalação Kubectl
      ansible.builtin.apt:
        name: kubectl
        state: present
        update_cache: yes